/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NotFoundError
 */
export interface NotFoundError {
  /**
   * エラーメッセージ
   * @type {string}
   * @memberof NotFoundError
   */
  message?: string;
}

/**
 * Check if a given object implements the NotFoundError interface.
 */
export function instanceOfNotFoundError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function NotFoundErrorFromJSON(json: any): NotFoundError {
  return NotFoundErrorFromJSONTyped(json, false);
}

export function NotFoundErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NotFoundError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, "message") ? undefined : json["message"],
  };
}

export function NotFoundErrorToJSON(value?: NotFoundError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
  };
}
