/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SkilltagsPost400Response
 */
export interface SkilltagsPost400Response {
  /**
   * エラーメッセージ
   * @type {string}
   * @memberof SkilltagsPost400Response
   */
  message?: string;
}

/**
 * Check if a given object implements the SkilltagsPost400Response interface.
 */
export function instanceOfSkilltagsPost400Response(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SkilltagsPost400ResponseFromJSON(
  json: any,
): SkilltagsPost400Response {
  return SkilltagsPost400ResponseFromJSONTyped(json, false);
}

export function SkilltagsPost400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SkilltagsPost400Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, "message") ? undefined : json["message"],
  };
}

export function SkilltagsPost400ResponseToJSON(
  value?: SkilltagsPost400Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
  };
}
