/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * １ユーザーの注釈自身
 * @export
 * @interface UserNoteOwn
 */
export interface UserNoteOwn {
  /**
   * ラベル
   * @type {string}
   * @memberof UserNoteOwn
   */
  label?: string;
  /**
   * メモ
   * @type {string}
   * @memberof UserNoteOwn
   */
  memo?: string;
}

/**
 * Check if a given object implements the UserNoteOwn interface.
 */
export function instanceOfUserNoteOwn(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserNoteOwnFromJSON(json: any): UserNoteOwn {
  return UserNoteOwnFromJSONTyped(json, false);
}

export function UserNoteOwnFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserNoteOwn {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    label: !exists(json, "label") ? undefined : json["label"],
    memo: !exists(json, "memo") ? undefined : json["memo"],
  };
}

export function UserNoteOwnToJSON(value?: UserNoteOwn | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    label: value.label,
    memo: value.memo,
  };
}
