/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UserCareer } from "./UserCareer";
import {
  UserCareerFromJSON,
  UserCareerFromJSONTyped,
  UserCareerToJSON,
} from "./UserCareer";

/**
 * １ユーザーのキャリアグループ
 * @export
 * @interface UserCareerGroup
 */
export interface UserCareerGroup {
  /**
   * キャリアグループラベル
   * @type {string}
   * @memberof UserCareerGroup
   */
  label?: string;
  /**
   * １ユーザーのキャリアグループのキャリア群
   * @type {Array<UserCareer>}
   * @memberof UserCareerGroup
   */
  careers?: Array<UserCareer>;
}

/**
 * Check if a given object implements the UserCareerGroup interface.
 */
export function instanceOfUserCareerGroup(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserCareerGroupFromJSON(json: any): UserCareerGroup {
  return UserCareerGroupFromJSONTyped(json, false);
}

export function UserCareerGroupFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserCareerGroup {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    label: !exists(json, "label") ? undefined : json["label"],
    careers: !exists(json, "careers")
      ? undefined
      : (json["careers"] as Array<any>).map(UserCareerFromJSON),
  };
}

export function UserCareerGroupToJSON(value?: UserCareerGroup | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    label: value.label,
    careers:
      value.careers === undefined
        ? undefined
        : (value.careers as Array<any>).map(UserCareerToJSON),
  };
}
