/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * １ユーザーの注釈内の１要素
 * @export
 * @interface UserNoteItem
 */
export interface UserNoteItem {
  /**
   * 注釈内の１要素
   * @type {string}
   * @memberof UserNoteItem
   */
  text?: string;
}

/**
 * Check if a given object implements the UserNoteItem interface.
 */
export function instanceOfUserNoteItem(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserNoteItemFromJSON(json: any): UserNoteItem {
  return UserNoteItemFromJSONTyped(json, false);
}

export function UserNoteItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserNoteItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    text: !exists(json, "text") ? undefined : json["text"],
  };
}

export function UserNoteItemToJSON(value?: UserNoteItem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    text: value.text,
  };
}
