/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * １ユーザーのアクティビティ
 * @export
 * @interface UserActivity
 */
export interface UserActivity {
  /**
   * アクティビティ名
   * @type {string}
   * @memberof UserActivity
   */
  name?: string;
  /**
   * URL
   * @type {string}
   * @memberof UserActivity
   */
  url?: string;
  /**
   * アクティビティアイコン
   * @type {string}
   * @memberof UserActivity
   */
  icon?: string;
}

/**
 * Check if a given object implements the UserActivity interface.
 */
export function instanceOfUserActivity(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserActivityFromJSON(json: any): UserActivity {
  return UserActivityFromJSONTyped(json, false);
}

export function UserActivityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserActivity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    url: !exists(json, "url") ? undefined : json["url"],
    icon: !exists(json, "icon") ? undefined : json["icon"],
  };
}

export function UserActivityToJSON(value?: UserActivity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    url: value.url,
    icon: value.icon,
  };
}
