/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * １キャリアのタスク
 * @export
 * @interface CareerTask
 */
export interface CareerTask {
  /**
   * タスク名
   * @type {string}
   * @memberof CareerTask
   */
  name?: string;
  /**
   * タスク説明
   * @type {Array<string>}
   * @memberof CareerTask
   */
  description?: Array<string>;
}

/**
 * Check if a given object implements the CareerTask interface.
 */
export function instanceOfCareerTask(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CareerTaskFromJSON(json: any): CareerTask {
  return CareerTaskFromJSONTyped(json, false);
}

export function CareerTaskFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CareerTask {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
  };
}

export function CareerTaskToJSON(value?: CareerTask | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
  };
}
