/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * １スキルの属性
 * @export
 * @interface Skill
 */
export interface Skill {
  /**
   * スキルを一意に識別するキー
   * @type {number}
   * @memberof Skill
   */
  id?: number;
  /**
   * スキル名
   * @type {string}
   * @memberof Skill
   */
  name?: string;
  /**
   * スキルキー
   * @type {string}
   * @memberof Skill
   */
  key?: string;
  /**
   * URL
   * @type {string}
   * @memberof Skill
   */
  url?: string;
  /**
   * スキルタグキー
   * @type {string}
   * @memberof Skill
   */
  tagKey?: string;
}

/**
 * Check if a given object implements the Skill interface.
 */
export function instanceOfSkill(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SkillFromJSON(json: any): Skill {
  return SkillFromJSONTyped(json, false);
}

export function SkillFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Skill {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
    key: !exists(json, "key") ? undefined : json["key"],
    url: !exists(json, "url") ? undefined : json["url"],
    tagKey: !exists(json, "tagKey") ? undefined : json["tagKey"],
  };
}

export function SkillToJSON(value?: Skill | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    key: value.key,
    url: value.url,
    tagKey: value.tagKey,
  };
}
