/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * １スキルの属性
 * @export
 * @interface Skill
 */
export interface Skill {
  /**
   * スキルを一意に識別するキー
   * @type {number}
   * @memberof Skill
   */
  id?: number;
  /**
   * スキル名
   * @type {string}
   * @memberof Skill
   */
  name?: string;
  /**
   * スキルコード
   * @type {string}
   * @memberof Skill
   */
  code?: string;
  /**
   * URL
   * @type {string}
   * @memberof Skill
   */
  url?: string;
  /**
   * スキルタグコード
   * @type {string}
   * @memberof Skill
   */
  tagCode?: string;
}

/**
 * Check if a given object implements the Skill interface.
 */
export function instanceOfSkill(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SkillFromJSON(json: any): Skill {
  return SkillFromJSONTyped(json, false);
}

export function SkillFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Skill {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
    code: !exists(json, "code") ? undefined : json["code"],
    url: !exists(json, "url") ? undefined : json["url"],
    tagCode: !exists(json, "tagCode") ? undefined : json["tagCode"],
  };
}

export function SkillToJSON(value?: Skill | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    code: value.code,
    url: value.url,
    tagCode: value.tagCode,
  };
}
