/* tslint:disable */
/* eslint-disable */
/**
 * CV API
 * CV API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * １スキルタグの属性
 * @export
 * @interface SkillTag
 */
export interface SkillTag {
  /**
   * スキルタグを一意に識別するキー
   * @type {number}
   * @memberof SkillTag
   */
  id?: number;
  /**
   * スキルタグ名
   * @type {string}
   * @memberof SkillTag
   */
  name?: string;
  /**
   * スキルタグキー
   * @type {string}
   * @memberof SkillTag
   */
  key?: string;
}

/**
 * Check if a given object implements the SkillTag interface.
 */
export function instanceOfSkillTag(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SkillTagFromJSON(json: any): SkillTag {
  return SkillTagFromJSONTyped(json, false);
}

export function SkillTagFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SkillTag {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
    key: !exists(json, "key") ? undefined : json["key"],
  };
}

export function SkillTagToJSON(value?: SkillTag | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    key: value.key,
  };
}
